Reset deployment configuration to working state

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -49,14 +49,11 @@ echo "Deploying..."
 echo "Source branch: $SRC_BRANCH"
 echo "Deploy branch: $DEPLOY_BRANCH"
 
-# Skip the confirmation prompt if running in GitHub Actions
-if [[ -z "${GITHUB_ACTIONS}" ]]; then
-    read -r -p "Do you want to proceed? [y/N] " response
-    if [[ ! $response =~ ^([yY][eE][sS]|[yY])+$ ]]
-    then
-        echo "Aborting."
-        [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
-    fi
+read -r -p "Do you want to proceed? [y/N] " response
+if [[ ! $response =~ ^([yY][eE][sS]|[yY])+$ ]]
+then
+    echo "Aborting."
+    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
 fi
 
 # Check if there are any uncommitted changes
